sudo: false
language: node_js
cache:
  directories:
    - game/elm-stuff
node_js:
  - "4.4"
install:
  - npm install -g elm@0.17.1
before_script:
  - bash game/setup.sh
script:
  - cd game
  - elm make --yes --output game.html game.elm
  - ../bin/elm-format --validate *.elm