sudo: false
language: node_js
cache:
  directories:
    - tests/elm-stuff
    - example/elm-stuff
node_js:
  - "4.3"
install:
  - npm install -g elm@0.16.0
before_script:
  - bash example/setup.sh
#script:
#  - node tests/test.js
