sudo: false
language: node_js
cache:
  directories:
    - example/elm-stuff
node_js:
  - "4.3"
install:
  - npm install -g elm@0.17.0
before_script:
  - bash example/setup.sh
script:
  - ls
#  - node tests/test.js
